### ISSUE TITLE
There is no good example with the new methods

### ISSUE THREAD

**Issue by RoelRoel** [konmik/konmik.github.io#2]
getView() of RxPresenter is deprecated and we should use restartableXX and deliverXX methods for pushing data from RxPresenter into View.

There is no good explanation how these methods work. What is "latest onNext value"?

How do we set the user input from the view back to the models (no example of that either). This library should be simple. Maybe it is because I'm a little stupid but I don't understand a thing of it...

**Comment by konmik** [comment]
Hi,

How do you find a such description?

https://github.com/konmik/nucleus/wiki/Restartables
