### ISSUE TITLE
AsyncTaskLoader in MVP

### ISSUE THREAD

**Issue by donpaul120** [konmik/konmik.github.io#3]
What category are we going to place AysncTaskLoader or how do we Use Presenters with AsyncTaskLoader which is attached to a Fragment when using MVP Pattern

**Comment by konmik** [comment]
I would put it right into a recycle bin.

Loader is a piece if useless shit. It does not restart after a process restart. During a couple if versions of the support library it didn't even work after a configuration change. It has so ugly API I can't believe someone is using it. Bundle? Why bundle? Why so many callbacks? Why forceLoad? Etc.

I would not write Nucleus if loaders actually do the job they are supposed to do.

**Comment by donpaul120** [comment]
Okay, thanks, lol..
I have a View(Fragment) ,a Presenter  and a DataModel, someone said Presenters shouldn't contain any import from android, but in my Model which is going to be a persistent model, i need to get reference to SharedPreference, i can easily pass it through the view interface to the presenter, but then views are not suppose to know about the model.. how would this be done in MVP without dagger, and also to run background task like JobSchedules for network operation does this happen in the Presenter? if yes how do presenters get notified of Broadcast from JobService so as to update the View.... prolly i haven't gotten the whole MVP thing properly, im new to MVP  but i would like to understand. please don't be harsh on me.

**Comment by konmik** [comment]
Don't listen to somebody :D think yourself. If you need to access preferences from presenter, there is nothing wrong with it. It is not nice to use activity context in a presenter. 

It is not nice to use android api in a presenter if you're going to port presenter's code into j2objc or unit-test presenters without mocking, or something special like that.

P.S. I normally use preferences from views. There is no real need to put _all_ io into presenter, I prefer to put only asynchronous IO there. Preferences are normally small, so they do not take lots of time and they can be read on the main thread.

**Comment by smilecs** [comment]
how can someone load data from the network without the use of loaders? any suggestions

**Comment by donpaul120** [comment]
@smilecs Without Loaders
++ AsyncTask
++ Android HttpUrlConnection

You can load data from the network with this two :)
Note that this is a direct answer to your question. :D
