### ISSUE TITLE
KISS principle link unavailable on MVP page

### ISSUE THREAD

**Issue by RaggaJungler** [konmik/konmik.github.io#5]
The KISS principle link on MVP page (https://github.com/konmik/konmik.github.io/wiki/Introduction-to-Model-View-Presenter-on-Android) leads to 404 Not Found

**Comment by konmik** [comment]
Oh my gosh. Thank you for the report! You can find it here for now: 

http://web.archive.org/web/20160206225831/https://people.apache.org/~fhanik/kiss.html
