### ISSUE TITLE
It's misleading to use "thread" when speaking of Presenter in "MVP example 01"

### ISSUE THREAD

**Issue by farmazon3000** [konmik/konmik.github.io#7]
https://github.com/konmik/konmik.github.io/wiki/Introduction-to-Model-View-Presenter-on-Android
`Technically speaking, MainPresenter has three threads of events: onNext, onError, onTakeView.`
It's misleading to use "thread" here - I think you did not mean a [Thread](http://developer.android.com/reference/java/lang/Thread.html). Please change it.

**Comment by konmik** [comment]
Done! Thanks :)
